### ISSUE TITLE
Failed to run in OpenShift

### ISSUE THREAD

**Issue by jstakun** [cescoffier/quarkus-granite-rag-demo#1]
Hello

When I tried to run your demo on OpenShift it fails during loading txt documents with following exception:

2024-10-29 08:33:07,048 INFO  [me.esc.gra.rag.Ingestion] (main) Ingesting 2 documents
2024-10-29 08:33:07,121 WARN  [org.inf.HOTROD] (main) ISPN004001: Could not find 'hotrod-client.properties' file in classpath, using defaults.
2024-10-29 08:33:07,176 INFO  [org.inf.HOTROD] (main) ISPN004074: Native Epoll transport not available, using NIO instead: io.netty.channel.epoll.Epoll
2024-10-29 08:33:07,177 INFO  [org.inf.HOTROD] (main) ISPN004108: Native IOUring transport not available, using NIO instead: io.netty.incubator.channel.uring.IOUring
2024-10-29 08:33:07,390 INFO  [org.inf.HOTROD] (main) ISPN004021: Infinispan version: Infinispan 'I'm Still Standing' 15.0.3.Final
2024-10-29 08:33:07,397 ERROR [me.esc.gra.rag.Ingestion] (main) Failed to load text documents from dir documents: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [-9374VJkmAmPjXHvPYlyIbOIgzY]: jakarta.enterprise.inject.CreationException: Null contextual instance was produced by a normal scoped synthetic bean: SYNTHETIC bean [class=org.infinispan.client.hotrod.RemoteCacheManager, id=3e5ozT9gyWKQ9VvCN1iNcOXJaqs]
	at io.quarkiverse.langchain4j.infinispan.InfinispanEmbeddingStore_-9374VJkmAmPjXHvPYlyIbOIgzY_Synthetic_Bean.doCreate(Unknown Source)
	at io.quarkiverse.langchain4j.infinispan.InfinispanEmbeddingStore_-9374VJkmAmPjXHvPYlyIbOIgzY_Synthetic_Bean.create(Unknown Source)
	at io.quarkiverse.langchain4j.infinispan.InfinispanEmbeddingStore_-9374VJkmAmPjXHvPYlyIbOIgzY_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c7(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at io.quarkiverse.langchain4j.infinispan.InfinispanEmbeddingStore_-9374VJkmAmPjXHvPYlyIbOIgzY_Synthetic_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkiverse.langchain4j.infinispan.InfinispanEmbeddingStore_-9374VJkmAmPjXHvPYlyIbOIgzY_Synthetic_ClientProxy.addAll(Unknown Source)
	at dev.langchain4j.store.embedding.EmbeddingStoreIngestor.ingest(EmbeddingStoreIngestor.java:198)
	at me.escoffier.granite.rag.Ingestion.<init>(Ingestion.java:46)
	at me.escoffier.granite.rag.Ingestion_Bean.doCreate(Unknown Source)
	at me.escoffier.granite.rag.Ingestion_Bean.create(Unknown Source)
	at me.escoffier.granite.rag.Ingestion_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at me.escoffier.granite.rag.Ingestion_Bean.get(Unknown Source)
	at me.escoffier.granite.rag.Ingestion_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:559)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:539)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:572)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:339)
	at me.escoffier.granite.rag.Ingestion_Observer_Synthetic_0bFjs-gRIEuHVtNvurKUgNIPE_k.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: jakarta.enterprise.inject.CreationException: Null contextual instance was produced by a normal scoped synthetic bean: SYNTHETIC bean [class=org.infinispan.client.hotrod.RemoteCacheManager, id=3e5ozT9gyWKQ9VvCN1iNcOXJaqs]
	at org.infinispan.client.hotrod.RemoteCacheManager_3e5ozT9gyWKQ9VvCN1iNcOXJaqs_Synthetic_Bean.doCreate(Unknown Source)
	at org.infinispan.client.hotrod.RemoteCacheManager_3e5ozT9gyWKQ9VvCN1iNcOXJaqs_Synthetic_Bean.create(Unknown Source)
	at org.infinispan.client.hotrod.RemoteCacheManager_3e5ozT9gyWKQ9VvCN1iNcOXJaqs_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.c11(Unknown Source)
	at io.quarkus.arc.generator.Default_jakarta_enterprise_context_ApplicationScoped_ContextInstances.computeIfAbsent(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at org.infinispan.client.hotrod.RemoteCacheManager_3e5ozT9gyWKQ9VvCN1iNcOXJaqs_Synthetic_ClientProxy.arc$delegate(Unknown Source)
	at org.infinispan.client.hotrod.RemoteCacheManager_3e5ozT9gyWKQ9VvCN1iNcOXJaqs_Synthetic_ClientProxy.administration(Unknown Source)
	at io.quarkiverse.langchain4j.infinispan.InfinispanEmbeddingStore.<init>(InfinispanEmbeddingStore.java:48)
	at io.quarkiverse.langchain4j.infinispan.InfinispanEmbeddingStore$Builder.build(InfinispanEmbeddingStore.java:173)
	at io.quarkiverse.langchain4j.infinispan.runtime.InfinispanEmbeddingStoreRecorder$1.apply(InfinispanEmbeddingStoreRecorder.java:30)
	at io.quarkiverse.langchain4j.infinispan.runtime.InfinispanEmbeddingStoreRecorder$1.apply(InfinispanEmbeddingStoreRecorder.java:17)
	at io.quarkiverse.langchain4j.infinispan.InfinispanEmbeddingStore_-9374VJkmAmPjXHvPYlyIbOIgzY_Synthetic_Bean.createSynthetic(Unknown Source)
	... 49 more

Can you advice please?

**Comment by cescoffier** [comment]
Seems to be an infinispan issue. @karesti may be able to help. 

You can switch to another vector store (I used PG Vector on openshift).

**Comment by jstakun** [comment]
Sure. Thanks! 
If only possible I would prefer to use Infinispan.

**Comment by karesti** [comment]
@jstakun did you include the file to be in the native executable ?

**Comment by karesti** [comment]
@jstakun for production, you need to add the production hosts for infinispan connection.

**Comment by karesti** [comment]
https://github.com/quarkusio/quarkus-quickstarts/blob/main/infinispan-client-quickstart/src/main/resources/application.properties#L2

**Comment by jstakun** [comment]
Thanks. I didn't notice in production mode I must deploy external infinispan instance
